// +build !ignore_autogenerated

/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by annotation-gen. DO NOT EDIT.

package examples

import (
	"encoding/json"

	"github.com/u2takey/go-annotation/pkg/lib"
	plugins "github.com/u2takey/go-annotation/pkg/plugins"
	"k8s.io/klog"
)

func init() {
	b := new(plugins.Description)
	err := json.Unmarshal([]byte("{\"body\":\"a\"}"), b)
	if err != nil {
		klog.Fatal("unmarshal json failed", err)
		return
	}
	lib.RegisterAnnotation(new(A), b)
}

func (s *A) Description() string {
	return ""
}

func init() {
	b := new(plugins.Description)
	err := json.Unmarshal([]byte("{\"body\":\"b\"}"), b)
	if err != nil {
		klog.Fatal("unmarshal json failed", err)
		return
	}
	lib.RegisterAnnotation(new(B), b)
}

func (s *B) Description() string {
	return ""
}
